Table empresa {
	id_emp integer [ pk, increment, not null, unique ]
	desc_emp varchar
}

Table sucursal {
	id_suc integer [ pk, increment, not null, unique ]
	direc_suc varchar [ unique ]
	desc_suc varchar [ unique ]
	email_suc varchar [ unique ]
	num_tel_suc integer
	fecha_de_apertur_suc date
	hora_de_a pertura_suc timestamp
	id_emp integer
}

Table empleado {
	id_emple integer [ pk, increment, not null, unique ]
	nom_emple varchar
	apell_emple varchar
	ci_emple integer
	num_emple integer
	emial_emple varchar
	fecha_de_ingreso_emple date
	cargo_emple varchar
	id_suc integer
	id_cajero integer
}

Table item {
	id_item integer [ pk, increment, not null, unique ]
	desc_item varchar
	prec_item decimal
}

Table stock {
	id_stock integer [ pk, increment, not null, unique ]
	id_item integer
	cant_stock integer
	id_suc integer
}

Table pedido_venta_cab {
	id_pedido_venta_cab integer [ pk, increment, not null, unique ]
	num_pedido integer
	fecha_pedido date
}

Table pedido_venta_det {
	id_pedido_venta_det integer [ pk, increment, not null, unique ]
	desc_pedido varchar
	precio_pedido integer
	cant_solicitada integer
	id_pedido_venta_cab integer
	id_stock integer
	id_cliente integer
}

Table cliente {
	id_cliente integer [ pk, increment, not null, unique ]
	nom_cliente varchar
	apelli_cliente varchar
	ci_cliente integer
	ruc_cliente integer [ not null ]
	tel_cliente integer
	estado_cliente varchar
}

Table cajero {
	id_cajero integer [ pk, increment, not null, unique ]
	nom_cajero varchar
	apell_cajero varchar
	ci_cajero integer
	email_cajero varchar
	id_horario_de_caja integer
}

Table horario_de_caja {
	id_horario_de_caja integer [ pk, increment, not null, unique ]
	apertura_caja timestamp
	cierre_de_caja timestamp
}

Ref fk_empresa_id_emp_sucursal {
	empresa.id_emp < sucursal.id_emp [ delete: restrict, update: cascade ]
}

Ref fk_empleado_id_suc_sucursal {
	empleado.id_suc - sucursal.id_suc [ delete: restrict, update: cascade ]
}

Ref fk_item_id_item_stock {
	item.id_item - stock.id_item [ delete: restrict, update: cascade ]
}

Ref fk_sucursal_id_suc_stock {
	sucursal.id_suc < stock.id_suc [ delete: restrict, update: cascade ]
}

Ref fk_pedido_venta_cab_id_pedido_venta_cab_pedido_venta_det {
	pedido_venta_cab.id_pedido_venta_cab > pedido_venta_det.id_pedido_venta_cab [ delete: restrict, update: cascade ]
}

Ref fk_stock_id_stock_pedido_venta_det {
	stock.id_stock > pedido_venta_det.id_stock [ delete: restrict, update: cascade ]
}

Ref fk_empleado_id_cajero_cajero {
	empleado.id_cajero - cajero.id_cajero [ delete: restrict, update: cascade ]
}

Ref fk_horario_de_caja_id_horario_de_caja_cajero {
	horario_de_caja.id_horario_de_caja < cajero.id_horario_de_caja [ delete: restrict, update: cascade ]
}

Ref fk_cliente_id_cliente_pedido_venta_det {
	cliente.id_cliente < pedido_venta_det.id_cliente [ delete: restrict, update: cascade ]
}